version: "3.7"

services:
  masjidy:
    build: .
    command: node server.js
    ports:
      - target: 3000
        published: 3000
    env_file:
      - .env
    depends_on:
      - postgresql
      - redis
  redis:
    image: redis:alpine
    ports:
      - target: 6379
        published: 6379

  postgresql:
    image: postgres
    environment:
      - POSTGRES_DB=MasjidyDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
